set_property SRC_FILE_INFO {cfile:c:/Users/johnj/dev/ece350/FatMan/FatMan.srcs/sources_1/ip/ila_0/ila_0/ila_0_in_context.xdc rfile:../../../../../FatMan.srcs/sources_1/ip/ila_0/ila_0/ila_0_in_context.xdc id:1 order:EARLY scoped_inst:debugger} [current_design]
set_property SRC_FILE_INFO {cfile:C:/Users/johnj/dev/ece350/processor/master.xdc rfile:../../../../../../processor/master.xdc id:2} [current_design]
set_property SRC_FILE_INFO {cfile:C:/Users/johnj/dev/ece350/FatMan/FatMan.runs/synth_1/dont_touch.xdc rfile:../../../dont_touch.xdc id:3} [current_design]
set_property src_info {type:SCOPED_XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 10 [get_pins debugger/clk]
set_property src_info {type:SCOPED_XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells debugger]
set_property src_info {type:XDC file:2 line:10 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 100.000 -name sys_clk_pin -waveform {0.000 50.000} -add [get_ports CLK10MHZ]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells debugger]
